M48
; DRILL file KiCad 10.0.1 date 2026-05-12T08:47:06
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-12T08:47:06-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X69.115Y-28.205
X74.895Y-28.205
T2
X152.075Y-33.425
X163.505Y-33.425
M30
