M48
; DRILL file KiCad 10.0.1 date 2026-05-09T20:51:15
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-05-09T20:51:15-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X2.7211Y-1.1094
X2.9486Y-1.1094
T2
X5.9872Y-1.3159
X6.4372Y-1.3159
M30
