M48
; DRILL file KiCad 10.0.1 date 2026-06-30T19:37:07
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-06-30T19:37:07-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.6616Y-1.1102
X4.8892Y-1.1102
T2
X7.9324Y-1.2915
X8.3824Y-1.2915
M30
